### ISSUE TITLE
Unable to create an instance of the NiFi Cluster based on the env(dev, stage etc) value

### ISSUE THREAD

**Issue by automationfirst** [Chaffelson/nipyapi#145]
* Nipyapi version: 0.13
* NiFi version: nifi-1.8.0
* NiFi-Registry version: NA
* Python version: Python 3.7.4
* Operating System: Windows 2008 Server

### Description
I was trying to create an instance of the NiFi Cluster based on the env value. Below is the excerpt of the code. 

Code
-----
envs = ['dev','stage']
for env in envs:
    c = Cluster(env)
    print(c.get_cluster_root())

The code is only returning the root of the NiFi Cluster only for the environment, which I'm passing first. For example, I will ony get NiFi root value of the DEV cluster. It is ignoring the stage environment variable in this case.

The code did not crash. Also there were no errors. Just that it does not return the seperate root values for each environment

### Urgency

I'm working on the workaround for this issue. The issue is urgent for now.

**Comment by Chaffelson** [comment]
This is expected behaviour, the rest client is lazily instantiated at the
first API call and has no automated logic to recognise that you want to
switch to another environment.
There is a utility call 'set_endpoint' available to help swap between
environments. You may wish to write a wrapper function to handle
environment swaps in your preferred manner.
You may also wish to take care with credentials between environments when
working with security as well.
