### ISSUE TITLE
PyPi Download Link is Broken

### ISSUE THREAD

**Issue by davidmargolis** [Chaffelson/nipyapi#254]
* NiPyApi version: 0.16.1

### Description

The [Download](https://github.com/Chaffelson/nipyapi/archive/0.16.1.tar.gz) button on [PyPi/NiPyApi](https://pypi.org/project/nipyapi/) page should direct to a page that allows you to download the project rather than getting a 404 error. (This is a different function than the Download files link)

### What I Did

1. Go to [PyPi/NiPyApi](https://pypi.org/project/nipyapi/)
2. Click [Download](https://github.com/Chaffelson/nipyapi/archive/0.16.1.tar.gz) button under Project links

Error -`404: Not Found`

**Comment by Chaffelson** [comment]
so the problem here appears to be that Pypi has autogenerated that URL and has got it wrong, if you look closely the tag name for the release is v0.16.1, but pypi is looking for 0.16.1, omitting the 'v' at the front.
Looking on Pypi there seems to be no way to control this, but installs still appear to be working as expected so I think this is just a peculiarity of their website.
