### ISSUE TITLE
Unable to create DBCP controller Database Driver Location(s) property 

### ISSUE THREAD

**Issue by narasimhatejav** [Chaffelson/nipyapi#285]
* Nipyapi version: 0.16.2
* NiFi version: 0.13.2
* Python version: 3.8.3
* Operating System: Windows

### Description

I am trying create **org.apache.nifi.dbcp.DBCPConnectionPool** through nipyapi but when i am updating the properties of connection pool only one property is not getting updated. Instead of updating it with the value it is creating duplicate property

### What I Did

These are the configuration properties :

'dbcp_properties = {"Database Connection URL":"jdbc:mysql://localhost:3306/world","Database Driver Class Name":"com.mysql.jdbc.Driver",
                   "Database Driver Location(s)":"C://nifi_test//mysql-connector-java-8.0.26//mysql-connector-java-8.0.26.jar",
                   "Database User":"root","Password":"root"}'

Issue in creating properties:

![image](https://user-images.githubusercontent.com/25453419/130597336-7665d8a5-3af3-4b4b-95d7-b7c15aa00dbb.png)

Instead of updating the value in  **Database Driver Location(s)** it is creating a duplicate property with the same name 

![image](https://user-images.githubusercontent.com/25453419/130597635-306f996b-e0a3-43e8-9539-ea93fdbfc216.png)

The issue is only with this property rest everything is working fine.

can you please let us know is there is different way to update the value?

### Urgency

It is blocking the flow.

**Comment by Chaffelson** [comment]
I think I can see how this would be an issue, can you please share the sample code you have for fetching the Processor properties, updating them, then submitting the Update?

**Comment by Kapkiai** [comment]
@narasimhatejav The problem here is when the display name differs from the actual name of the property. Latest NiFi version has the right name to be used in documentation of all components. e.g. a new column has beed added in the documentation called "API Name", use this to configure the processor. Example for
ConsumeKafka_2_6 processor:
https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-kafka-2-6-nar/1.19.1/org.apache.nifi.processors.kafka.pubsub.ConsumeKafka_2_6/index.html
Thanks @Chaffelson for this great work!!
