### ISSUE TITLE
Leave location tuple by default for method "deploy_flow_version"

### ISSUE THREAD

**Issue by maykiwo** [Chaffelson/nipyapi#342]
* Nipyapi version:  '0.19.1'
* NiFi version: '1.23.2'
* NiFi-Registry version: '1.18.'
* Python version: 3.9.8
* Operating System: Rocky 8

### Description

How to setup the default location ?

### What I Did

When deploy the flow in the nifi client how it is possible to leave the Nifi instance to choice the location itself ?

Thanks a lot

**Comment by Chaffelson** [comment]
Unfortunately the NiFi server does not have a function for this, because it assumes that it is being operated interactively from a browser session.
We could add a feature to NiPy to calculate a likely location for the Flow or Object to be deployed on the canvas, and I did historically have some example code to do so, but testing it and not impacting existing flows was troublesome so I never chased it down.

Is it not easy enough to set your own location in your deployment script? Or would you rather that `deploy_flow_version` had a default location like `(0,0)` as a tuple in NiPy?
